FROM ubuntu:20.04
MAINTAINER Kuflievskiy Aleksey <kuflievskiy@gmail.com>

LABEL "name"="Webserver"
LABEL "version"="0.0.2"

# Labels.
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.build-date="2019-04-09"
LABEL org.label-schema.name="kuflievskiy/docker-project-skeleton"
LABEL org.label-schema.maintainer="kuflievskiy@gmail.com"
LABEL org.label-schema.description="Docker project skeleton"
LABEL org.label-schema.url="https://github.com/kuflievskiy/docker-project-skeleton"
LABEL org.label-schema.vcs-url="https://github.com/kuflievskiy/docker-project-skeleton"
LABEL org.label-schema.version="1.0"
LABEL org.label-schema.docker.cmd="docker-compose up -d --build"

# This section could be used on Ubuntu during the development
# Usage example: docker exec container_webserver chown -R $USER /var/www/html
#
# ARG LOCAL_USER
# ARG LOCAL_UID
# ARG LOCAL_GID
#
# Create a user group '$LOCAL_USER'
# RUN addgroup $LOCAL_USER --gid $LOCAL_GID
#
# Create a user '$LOCAL_USER'
# RUN adduser --system --uid $LOCAL_UID --home /var/www/html $LOCAL_USER
#
# usermod -a -G groupname username
# RUN usermod -a -G root $LOCAL_USER
#
# Chown all the files to the app user.
# RUN chown -R $LOCAL_USER:$LOCAL_USER /var/www/html

# Install packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y software-properties-common
RUN DEBIAN_FRONTEND=noninteractive LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php

RUN apt-get -y update
RUN apt-get -y install \
    supervisor \
    git \
    apache2 \
    libapache2-mod-php8.0 \
    curl \
    wget \
    libnss3-dev \
    php8.0-curl \
    php8.0-mysqli \
    php8.0-zip zip unzip \
    php8.0-gd \
    php8.0-xml \
    php8.0-mbstring && \
  echo "ServerName localhost" >> /etc/apache2/apache2.conf

# installing soap
#RUN apt-get update -y \
#  && apt-get install -y \
#    libxml2-dev \
#    php8.0-soap

# Adds Ruby 2.1 to Ubuntu 14.04
# and install "Web Package Update checker"
#RUN add-apt-repository ppa:brightbox/ruby-ng -y && \
#    apt-get update && \
#    apt-get install ruby2.1 -y && \
#    gem install web-puc

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# config to enable .htaccess
#ADD etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

RUN apt-get -y install \
 php8.0-xdebug \
 vim

# Install sSMTP service.
RUN apt-get update && \
    apt-get install -y ssmtp && \
    apt-get clean

# Configure /app folder with sample app
#RUN git clone https://github.com/kuflievskiy/drupal /app
#RUN mkdir -p /app && rm -fr /var/www/html && ln -s /app /var/www/html

#Environment variables to configure php
ENV PHP_UPLOAD_MAX_FILESIZE 10M
ENV PHP_POST_MAX_SIZE 10M

# Add volumes
# /var/lib/docker/volumes/%folder-name%
# VOLUME  ["/etc/mysql", "/var/lib/mysql", "/var/log/apache2" ]

COPY install-scripts/wordpress.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/wordpress.sh

COPY install-scripts/drupal.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/drupal.sh

WORKDIR /var/www/html

EXPOSE 80
EXPOSE 443

CMD ["apachectl", "-DFOREGROUND"]